version: '3.8'

services:
  django:
    build: ./lesspass
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./lesspass:/usr/src/app
    env_file:
      - ./lesspass/.env
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8000:8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: "rabbitmq:latest"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"

  celery:
    build: ./lesspass
    command: celery -A core worker --loglevel=info
    volumes:
      - ./lesspass:/usr/src/app
    depends_on:
      - rabbitmq
      - db
    env_file:
      - ./lesspass/.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./django/static:/usr/src/app/static
      - ./django/media:/usr/src/app/media
    depends_on:
      - django

volumes:
  postgres_data:
